[package]
name = "sql-json-path"
version = "0.2.0"
edition = "2021"
description = "SQL/JSON Path implementation in Rust."
repository = "https://github.com/risingwavelabs/sql-json-path"
keywords = ["json", "jsonpath", "sql"]
categories = ["data-structures"]
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = "0.4"
chrono = "0.4"
jsonbb = { version = "0.2", optional = true }
nom = "7"
regex = "1"
serde_json = { version = "1", features = ["arbitrary_precision"] }
simd-json = { version = "0.16", optional = true }
thiserror = "2"

[dev-dependencies]
libtest-mimic = "0.8"

[[test]]
name = "pg_jsonb_jsonpath"
path = "tests/pg_jsonb_jsonpath.rs"
harness = false
